/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 gear.glb -t -T -k -K -b s 
Files: gear.glb [1.94MB] > C:\Users\owner\Desktop\lead_flow\public\3d\home\gear\gear-transformed.glb [141.97KB] (93%)
Author: Ali107_YT (https://sketchfab.com/Ali_Army107)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-gear-defc6569f42543f1ad5501de36d65ec8
Title: Simple Gear
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { DissolveMaterial } from '@/_components/client/home/components/3d/DissolveMaterial'
import { useDissolveBaseMaterial } from '@/_components/client/home/components/3d/helpers/useDissolveMaterial'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_Material001_0: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export default function Gear(props: any) {
  const { nodes, materials } = useGLTF('/3d/home/gear/gear-transformed.glb') as unknown as GLTFResult
  const baseMat1 = useDissolveBaseMaterial();
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Cylinder_Material001_0" geometry={nodes.Cylinder_Material001_0.geometry} material={baseMat1} rotation={[-Math.PI / 6, 0, 0]} scale={100} >
          
                    <DissolveMaterial
                      baseMaterial={baseMat1}
                      visible={props.disolveVisible}
                      onFadeOut={props.onFadeOut}
                    />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/home/gear/gear-transformed.glb')
